Vagrant.configure("2") do |config|
  config.vm.box = "generic/fedora28"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.ssh.private_key_path = "~/.ssh/id_rsa"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.cpus = "2"
    vb.memory = "1024"
   end

  config.vm.provision "shell",
    path: "../scripts/ansible-pull.sh",
    privileged: false

end
